language: java
jdk:
  - openjdk8
branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
  - zip -r AWSProj *
  - mkdir -p deploy
  - mv AWSProj.zip deploy/AWSProj.zip

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/AWSProj.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: chae-springboot-aws-proj-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: chae-springboot-aws-proj-build
    key: AWSProj.zip
    bundle_type: zip
    application: chae-springboot-aws-proj
    deployment_group: chae-springboot-aws-proj-group
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료시 메일로 알림
notification:
    email:
      recipients:
        - bubsakk@gmail.com
